swagger: '2.0'
# Example see: https://github.com/hjacobs/connexion-example/blob/master/swagger.yaml
info:
  title: Summarize API
  version: "0.1"
  description: API to summarize text, using LSA (Latent Semantic Analysis)
consumes:
  - application/json
produces:
  - application/json

basePath: "/api"

#security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
#  - oauth2: [uid]
paths:
  /summarize:
    get:
      tags: 
        - "summarize"
      operationId: app.get_summary
      summary: Creates a summary from the input text
      parameters:
        - name: text
          in: query
          type: string
      responses:
        200:
          description: Return a summary of the text
          schema:
            type: object
            properties:
              summary:
                type: string